version: '3'

services:
    nginx:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - frontend
        - backend
  frontend:
      image: frontend-example-docker
      environment:
        - API_URL=http://localhost/api

    backend:
      image: backend-example-docker
      environment:
        - REDIS=redis
        - DB_USERNAME=user
        - DB_PASSWORD=password
        - DB_HOST=db
      depends_on:
        - db
    db:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=user
    redis:
      image: redis
